### ISSUE TITLE
There is a little bug here. It's not responsive on mobile screens (Details Inside)

### ISSUE THREAD

**Issue by NomanBaigA** [calebcadainoo/wayamoney-download-page#4]
The mobile image is appearing at the bottom of the page on smaller devices. (Screenshots included)

How it should be - 
1 - It should disappear in small screen devices (Smartphones)
2 - Or it should appear smaller

Screenshot of the problem - 

1
![Screenshot 1](https://github.com/calebcadainoo/wayamoney-download-page/assets/49509445/44948596-cabc-4fcb-88ae-e95200ba13e0)

2
![Screenshot 2](https://github.com/calebcadainoo/wayamoney-download-page/assets/49509445/1d707ba3-8941-4fe7-a54c-e21436ef53fb)

**Comment by calebcadainoo** [comment]
Visit the link on an actual device
Mobile Phone or Tablet
Resizing browser window doesn't always guarantee a good responsive view.
You can try for example Firefox Responsive Mode that's one of the best way to preview scalability.

![Screenshot_20230723-134152](https://github.com/calebcadainoo/wayamoney-download-page/assets/56970927/0084d291-c1d9-4c77-a95a-61941081be21)
